#
# Distributed Linear Algebra with Future (DLAF)
#
# Copyright (c) ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
#

spack:
  include:
    - /spack_environment/common.yaml
  specs:
    - dla-future-fortran@main +test +cscs-ci
  packages:
    blas:
      require:
        - intel-oneapi-mkl
    lapack:
      require:
        - intel-oneapi-mkl
    scalapack:
      require:
        - intel-oneapi-mkl +cluster
  view: false
  concretizer:
    unify:
      true
